# Generated by Django 3.2.25 on 2024-08-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('ability_element', models.CharField(choices=[('GR', 'Grass'), ('FR', 'Fire'), ('WA', 'Water'), ('LI', 'Lightning'), ('FT', 'Fighting'), ('PS', 'Psychic'), ('CL', 'Colorless'), ('DA', 'Darkness'), ('ME', 'Metal'), ('DR', 'Dragon'), ('FA', 'Fairy'), ('UN', 'Unknown')], default='UN', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_name', models.CharField(max_length=100)),
                ('HP', models.IntegerField()),
                ('length', models.FloatField()),
                ('weight', models.FloatField()),
                ('species', models.CharField(max_length=100)),
                ('pokemon_element', models.CharField(choices=[('GR', 'Grass'), ('FR', 'Fire'), ('WA', 'Water'), ('LI', 'Lightning'), ('FT', 'Fighting'), ('PS', 'Psychic'), ('CL', 'Colorless'), ('DA', 'Darkness'), ('ME', 'Metal'), ('DR', 'Dragon'), ('FA', 'Fairy'), ('UN', 'Unknown')], default='UN', max_length=2)),
                ('rarity', models.CharField(choices=[('CO', 'Common'), ('UN', 'Uncommon'), ('RA', 'Rare'), ('PR', 'Promo')], default='CO', max_length=2)),
                ('other', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon_Ability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firts_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='first_ability', to='pokemons.ability')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemons.pokemon')),
                ('second_ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='second_ability', to='pokemons.ability')),
            ],
        ),
    ]
